import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is auto-regenerated by `next dev`/`next build` on every
    // run and always contains the triple-slash reference ESLint flags below
    // — not something to hand-edit or lint.
    ignores: [".next/**", "node_modules/**", "out/**", "next-env.d.ts"],
  },
  {
    // Server Actions bound for useActionState (e.g. deleteRecordAction)
    // must keep the (prevState, formData) signature even when a given
    // action doesn't read one of them — underscore-prefixed params mark
    // that as intentional rather than a real unused-variable bug.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default eslintConfig;
